<?php

/**
 * PluginaPageToCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginaPageToCategoryTable extends Doctrine_Table
{

  /**
   * Returns an instance of this class.
   *
   * @return object PluginaPageToCategoryTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('PluginaPageToCategory');
  }

  public function mergeCategory($old_id, $new_id)
  {
    Doctrine::getTable('aCategory')->mergeCategory($old_id, $new_id, 'aPageToCategory', 'category_id', true, 'page_id');
  }

}