<?php
/**
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * @package    apostrophePlugin
 * @subpackage    model
 * @author     P'unk Avenue <apostrophe@punkave.com>
 */
class PluginaLuceneUpdateTable extends Doctrine_Table
{

  /**
   * DOCUMENT ME
   * @param mixed $page
   */
  static public function requestUpdate($page)
  {
    $update = new aLuceneUpdate();
    $update->page_id = $page->getId();
    $update->culture = $page->getCulture();
    $update->save();
  }
}
