<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginaPageTable extends Doctrine_Table
{
	// We always join with all of the current slots for the proper culture in this simplest page-getter method.
	// Otherwise we wreck the slot cache for slots on the page, etc., can't see titles or see the wrong versions
	// and cultures of slots. This is inefficient in some situations, but the
	// right response to that is to recognize when you're about to fetch a page
	// that has already been fetched and just reuse it. I can't make that call
	// for you at the model level

  static public function retrieveBySlug($slug, $culture = null)
  {
    return self::retrieveBySlugWithSlots($slug, $culture);
  }

	// CAREFUL: if you are not absolutely positive that you won't need other slots for this
	// page (ie it is NOT the current page), then don't use this. Use retrieveBySlugWithSlots

  // If culture is null you get the current user's culture,
  // or sf_default_culture if none is set or we're running in a task context
  static public function retrieveBySlugWithTitles($slug, $culture = null)
  {
    if (is_null($culture))
    {
      $culture = aTools::getUserCulture();
    }
    $query = self::queryWithTitles($culture);
    $page = $query->
      andWhere('p.slug = ?', $slug)->
      fetchOne();
    // In case Doctrine is clever and returns the same page object
    if ($page)
    {
      $page->clearSlotCache();
      $page->setCulture($culture);
    }
    return $page;
  }

  // If culture is null you get the current user's culture,
  // or sf_default_culture if none is set or we're running in a task context
  static public function retrieveBySlugWithSlots($slug, $culture = null)
  {
    if (is_null($culture))
    {
      $culture = aTools::getUserCulture();
    }
    $query = self::queryWithSlots(false, $culture);
    $page = $query->
      andWhere('p.slug = ?', $slug)->
      fetchOne();
    // In case Doctrine is clever and returns the same page object
    if ($page)
    {
      $page->clearSlotCache();
      $page->setCulture($culture);
    }
    return $page;
  }
  // If culture is null you get the current user's culture,
  // or sf_default_culture if none is set or we're running in a task context

  static public function queryWithTitles($culture = null)
  {
    return self::queryWithSlot('title', $culture);
  }

  // This is a slot name, like 'title'
  static public function queryWithSlot($slot, $culture = null)
  {
    if (is_null($culture))
    {
      $culture = aTools::getUserCulture();
    }
    $query = self::queryWithSlots(false, $culture)
      ->andWhere('a.name = ?', $slot);

    return $query;
  }

  // This is a slot type, like 'aRichText'
  static public function queryWithSlotType($slotType, $culture = null)
  {
    if (is_null($culture))
    {
      $culture = aTools::getUserCulture();
    }
    $query = self::queryWithSlots(false, $culture)
      ->andWhere('s.type = ?', $slotType);

    return $query;
  }

  // If culture is null you get the current user's culture,
  // or sf_default_culture if none is set or we're running in a task context

  static public function retrieveByIdWithSlots($id, $culture = null)
  {
    return self::retrieveByIdWithSlotsForVersion($id, false, $culture);
  }
  // If culture is null you get the current user's culture,
  // or sf_default_culture if none is set or we're running in a task context

  static public function retrieveByIdWithSlotsForVersion($id, $version, $culture = null)
  {
    if (is_null($culture))
    {
      $culture = aTools::getUserCulture();
    }
    $page = self::queryWithSlots($version, $culture)->
      andWhere('p.id = ?', array($id))->
      fetchOne();
    // In case Doctrine is clever and returns the same page object
    if ($page)
    {
      $page->clearSlotCache();
      // Thanks to Quentin Dugauthier for spotting that there were
      // still instances of this not being inside the if
      $page->setCulture($culture);
    }
    return $page;
  }

  /**
   * Gets a query for slots and media items for pages, used for when rendering a page.
   * @param int $version version of slot to query for, if false returns latest version of each slot
   * @param $culture culture to retrieve from, if null the current user's culture, or sf_default_culture if cone is set or we're running in a task context
   * @param Doctrine_Query $query
   * @return Doctrine_Query $query
   */
  public static function queryWithSlots($version = false, $culture = null, $query = null)
  {
    if(is_null($query))
    {
      $query = Doctrine::getTable('aPage')->createQuery('p');
    }
    if (is_null($culture))
    {
      $culture = aTools::getUserCulture();
    }

    // ACHTUNG: resist the temptation to move these into WHERE clauses.
    // It looks all sweet and innocent until you don't get any records back
    // and assume you have to recreate the global page... once on every page load.
    // That's why we LEFT JOIN in the first place
    $areaJoinArgs = array();
    $areaJoin = 'p.Areas a';
    if ($culture !== 'all')
    {
      $areaJoin .= ' WITH a.culture = ?';
      $areaJoinArgs[] = $culture;
    }
    $versionJoinArgs = array();
    $versionJoin = 'a.AreaVersions v';
    if ($version === false)
    {
      $versionJoin .= ' WITH a.latest_version = v.version';
    } else
    {
      $versionJoin .= ' WITH v.version = ?';
      $versionJoinArgs[] = $version;
    }
    
    $query->
      leftJoin($areaJoin, $areaJoinArgs)->
      leftJoin($versionJoin, $versionJoinArgs)->
      leftJoin('v.AreaVersionSlots avs')->
      leftJoin('avs.Slot s')->
      leftJoin('s.MediaItems m')->
      orderBy('avs.rank asc');

    return $query;
  }
   
  static private $treeObject = null;
  
  static public function treeTitlesOn()
  {
    self::treeSlotOn('title');
  }
  
  static public function treeSlotOn($slot)
  {
    $query = aPageTable::queryWithSlot($slot);
    self::$treeObject = Doctrine::getTable('aPage')->getTree();
    // I'm not crazy about how I have to set the base query and then
    // reset it, instead of simply passing it to getChildren. A
    // Doctrine oddity
    self::$treeObject->setBaseQuery($query);
  }
  
  static public function treeTitlesOff()
  {
    self::treeSlotOff();
  }
  
  static public function treeSlotOff()
  {
    self::$treeObject->resetBaseQuery();
  } 
  
  public function getLuceneIndexFile()
  {
    return aZendSearch::getLuceneIndexFile($this);
  }

  public function getLuceneIndex()
  {
    return aZendSearch::getLuceneIndex($this);
  }

  // This does the entire thing at one go, which may be too memory intensive.
  // The apostrophe:rebuild-search-index task instead invokes apostrophe:update-search-index
  // for batches of 100 pages
  public function rebuildLuceneIndex()
  {
    aZendSearch::purgeLuceneIndex($this);
    $pages = $this->createQuery('p')->innerJoin('p.Areas a')->execute(array(), Doctrine::HYDRATE_ARRAY);
    foreach ($pages as $page)
    {
      $cultures = array();
      foreach ($page['Areas'] as $area)
      {
        $cultures[$area['culture']] = true; 
      }
      $cultures = array_keys($cultures);
      foreach ($cultures as $culture)
      {
        $cpage = self::retrieveBySlugWithSlots($page['slug'], $culture);
        $cpage->updateLuceneIndex();
      }
    }
  }
  
  public function addSearchQuery(Doctrine_Query $q = null, $luceneQuery)
  {
    // Page searches are always specific to this user's culture
    $culture = aTools::getUserCulture();
    $luceneQuery = "+(text:($luceneQuery))";
    return aZendSearch::addSearchQuery($this, $q, $luceneQuery, $culture);
  }
  
  public function addSearchQueryWithScores(Doctrine_Query $q = null, $luceneQuery, &$scores)
  {
    // Page searches are always specific to this user's culture
    $culture = aTools::getUserCulture();
    $luceneQuery = "+(text:($luceneQuery))";
    return aZendSearch::addSearchQueryWithScores($this, $q, $luceneQuery, $culture, $scores);
  }
  
  // Just a hook used by the above
  public function searchLucene($query, $culture)
  {
    return aZendSearch::searchLucene($this, $query, $culture);
  }
  
  // Just a hook used by the above
  public function searchLuceneWithScores($query, $culture)
  {
    return aZendSearch::searchLuceneWithScores($this, $query, $culture);
  }

  // Returns engine page with the longest matching path.
  // We use a cache so that we don't wind up making separate queries
  // for every engine route in the application
  
  protected static $engineCacheUrl = false;
  protected static $engineCachePage = false;
  protected static $engineCacheRemainder = false;
  protected static $engineCacheFirstEnginePages = array();
  protected static $engineCachePagePrefix = false;
  
  static public function getMatchingEnginePage($url, &$remainder)
  {
    // Engines won't work on sites where the CMS is not mounted at the root of the site
    // unless we examine the a_page route to determine a prefix. Generate the route properly
    // then lop off the controller name, if any
    
    if ($url === self::$engineCacheUrl)
    {
      $remainder = self::$engineCacheRemainder;
      return self::$engineCachePage;
    }
    
    // if (self::$engineCachePagePrefix)
    // {
    //   $prefix = self::$engineCachePagePrefix;
    // }
    // else
    {
      $prefix = '';
      $dummyUrl = sfContext::getInstance()->getRouting()->generate('a_page', array('slug' => 'dummy', 'sf_culture' => aTools::getUserCulture()), false);
      $rr = preg_quote(sfContext::getInstance()->getRequest()->getRelativeUrlRoot(), '/');
      // The URL we're being asked to examine has already
      // lost its relative_root_url, so don't include $rr in
      // the prefix we attempt to remove
      if (preg_match("/^(?:\/\w+\.php)?$rr(.*)\/dummy$/", $dummyUrl, $matches))
      {
        $prefix = $matches[1];
      }
      self::$engineCachePagePrefix = $prefix;
    }
    $url = preg_replace('/^' . preg_quote($prefix, '/') . '/', '', $url);
    
    $urls = array();
    // Remove any query string
    $twig = preg_replace('/\?.*$/', '', $url);
    while (true)
    {
      if (($twig === '/') || (!strlen($twig)))
      {
        // Either we've been called for the home page, or we just
        // stripped the first slash and are now considering the home page
        $urls[] = '/';
        break;
      }
      $urls[] = $twig;
      if (!preg_match('/^(.*)\/[^\/]+$/', $twig, $matches))
      {
        break;
      }
      $twig = $matches[1];
    }
    $page = Doctrine_Query::create()->
      select('p.*, length(p.slug) as len')->
      from('aPage p')->
      whereIn('p.slug', $urls)->
      andWhere('p.engine IS NOT NULL')->
      orderBy('len desc')->
      limit(1)->
      fetchOne();
    self::$engineCachePage = $page;
    self::$engineCacheUrl = $url;
    self::$engineCacheRemainder = false;
    if ($page)
    {
      $remainder = substr($url, strlen($page->slug));
      self::$engineCacheRemainder = $remainder;
      return $page;
    }
    return false;
  }
  
  // Used when generating an engine link from a page other than the engine page itself.
  // Many engines are only placed in one location per site, so this is often reasonable.
  // Cache this for acceptable performance. Admin pages match first to ensure that the
  // Apostrophe menu always goes to the right place. If you have a public version of the same
  // engine and you want to link to it via link_to(), target it explicitly, see
  // aRouteTools::pushTargetEnginePage()
  
  static public function getFirstEnginePage($engine)
  {
    if (isset(self::$engineCacheFirstEnginePages[$engine]))
    {
      return self::$engineCacheFirstEnginePages[$engine];
    }
    $page = Doctrine_Query::create()->
     from('aPage p')->
     where('p.engine = ?', array($engine))->
     limit(1)->
     fetchOne();
    self::$engineCacheFirstEnginePages[$engine] = $page;
    return $page;
  }
  
  // Useful with queries aimed at finding a page; avoids the 
  // considerable expense of hydrating it
  static public function fetchOneSlug($query)
  {
    $query->limit(1);
    $data = $query->fetchArray();
    if (!count($data))
    {
      return false;
    }
    return $data[0]['slug'];
  }
  
  // Want to extend privilege checks? Override checkUserPrivilegeBody(). Read on for details
  
  // Check whether the user has sufficient privileges to access a page. This includes
  // checking explicit privileges in the case of pages that have them on sites where
  // there is a 'candidate group' for that privilege. $pageOrInfo can be a
  // Doctrine aPage object or an info structure like those returned by getAncestorsInfo() etc.
  
  // Sometimes you can't afford the overhead of an aPage object, thus this method.
  
  static $privilegesCache = array();
  
  // Static methods are tricky to override in PHP. Get an instance of the table and call a new
  // non-static version
  
  static public function checkPrivilege($privilege, $pageOrInfo, $user = false)
  {
    $table = Doctrine::getTable('aPage');
    return $table->checkUserPrivilege($privilege, $pageOrInfo, $user);
  }
  
  public function checkUserPrivilege($privilege, $pageOrInfo, $user)
  {
    if ($user === false)
    {
      $user = sfContext::getInstance()->getUser();
    }
    
    $username = false;
    if ($user->getGuardUser())
    {
      $username = $user->getGuardUser()->getUsername();
    }

    // Archived pages can only be visited by users who are permitted to edit them.
    // This trumps the less draconian privileges for viewing pages, locked or otherwise
    if (($privilege === 'view') && $pageOrInfo['archived'])
    {
      $privilege = 'edit';
    }
    else
    {
      // Individual pages can be conveniently locked for 
      // viewing purposes on an otherwise public site. This is
      // implemented as a separate permission. 
      if ($privilege === 'view') 
      {
        if ($pageOrInfo['view_is_secure'])
        {
          if ($pageOrInfo['view_guest'])
          {
            $privilege = 'view_locked';
          }
          else
          {
            // There are never 'sufficient' credentials for this so we wind up checking
            // for specific privileges. However if we can edit or manage the page
            // we can always view it
            $privilege = 'edit|manage|view_custom';
          }
        }
        else
        {
          if ($pageOrInfo['view_admin_lock'])
          {
            return $user->isAuthenticated() && $user->hasCredential('cms_admin');
          }
        }
      }
    }

    // If you can manage, you can also edit. Implement this 
    // in one place so we don't have to say it explicitly all over
    if ($privilege === 'edit')
    {
      $privilege = 'edit|manage';
    }

    if (isset(self::$privilegesCache[$username][$privilege][$pageOrInfo['id']]))
    {
      return self::$privilegesCache[$username][$privilege][$pageOrInfo['id']];
    }
    $result = $this->checkUserPrivilegeBody($privilege, $pageOrInfo, $user, $username);
    self::$privilegesCache[$username][$privilege][$pageOrInfo['id']] = $result;
    return $result;
  }
  
  // The privilege name has already been transformed if appropriate. The username has already been fetched
  // (false for a logged out user). The cache has already been checked. The return value of this call will
  // be cached by the checkUserPrivilege method. Override this method, calling the parent first and then
  // adding further checks as you deem necessary
  
  public function checkUserPrivilegeBody($privilege, $pageOrInfo, $user, $username)
  {
    $result = false;
    
    // Rule 1: admin can do anything
    // Work around a bug in some releases of sfDoctrineGuard: users sometimes
    // still have credentials even though they are not logged in
    if ($user->isAuthenticated() && $user->hasCredential('cms_admin'))
    {
      $result = true;
    }
    else
    {
      $privileges = explode("|", $privilege);
      foreach ($privileges as $privilege)
      {
        error_log("Privilege $privilege");
        // Rule 1a: if edit_admin_lock is set, only admins can edit or manage
        if (($privilege === 'edit') || ($privilege === 'manage'))
        {
          if ($pageOrInfo['edit_admin_lock'])
          {
            continue;
          }
        }
        
        $sufficientCredentials = sfConfig::get(
            "app_a_$privilege" . "_sufficient_credentials", false);
        $sufficientGroup = sfConfig::get(
            "app_a_$privilege" . "_sufficient_group", false);
            
        // Starting in 1.5 edit and manage share a candidate group
        if ($privilege === 'manage')
        {
          $privilegeForGroup = 'edit';
        }
        else
        {
          $privilegeForGroup = $privilege;
        }
        $candidateGroup = sfConfig::get(
            "app_a_$privilegeForGroup" . "_candidate_group", false);
            
        // By default users must log in to do anything, except for viewing an unlocked page
        $loginRequired = sfConfig::get(
            "app_a_$privilege" . "_login_required", 
            ($privilege === 'view' ? false : true));

        // Rule 2: if no login is required for the site as a whole for this
        // privilege, anyone can do it...
        if (!$loginRequired)
        {
          $result = true;
          break;
        }

        // Corollary of rule 2: if login IS required and you're not
        // logged in, bye-bye
        if (!$user->isAuthenticated())
        {
          continue;
        }

        if ($privilege !== 'view_custom')
        {
          // Rule 3: if there are no sufficient credentials and there is no
          // required or sufficient group, then login alone is sufficient. Common 
          // on sites with one admin. Exception: there is no such thing as sufficient
          // credentials for view_custom, the whole point is to check your
          // individual credentials
          if (($sufficientCredentials === false) && ($candidateGroup === false) && ($sufficientGroup === false))
          {
            // Logging in is the only requirement
            $result = true;
            break;
          }

          // Rule 4: if the user has sufficient credentials... that's sufficient!
          // Many sites will want to simply say 'editors can edit everything' etc
          if ($sufficientCredentials && 
            ($user->hasCredential($sufficientCredentials)))
          {
            $result = true;
            break;
          }
          if ($sufficientGroup && 
            ($user->hasGroup($sufficientGroup)))
          {
            $result = true;
            break;
          }
        }

        // Remaining cases require that the page be in the tree so explicit privileges can be applied
        // Failure to check this grants blanket access to all global slots
        if (!$pageOrInfo['lft'])
        {
          continue;
        }

        // Rule 5: if there is a candidate group, make sure the user is a member
        // before checking for explicit privileges for that user
        if ($candidateGroup && 
          (!$user->hasGroup($candidateGroup)))
        {
          // Nope
        }
        else
        {
          // The explicit case for users
          $user_id = $user->getGuardUser()->getId();
        
          // Privileges are no longer inherited. Instead there are generous tools for
          // explicitly copying a permission to all descendant pages, and then it is 
          // possible to modify them individually. There is also a lock option which
          // restricts edits or views to admins only and cannot be clobbered by a cascade. 
          // This is a good compromise that avoids forcing the full complexities of ACLs 
          // on admins while still allowing for a wide array of commonly encountered scenarios
          $accesses = Doctrine_Query::create()->
            select('a.*')->from('aAccess a')->innerJoin('a.Page p')->
            where("p.id = ? AND a.user_id = ? AND a.privilege = ?", array($pageOrInfo['id'], $user_id, $privilege))->
            limit(1)->
            execute(array(), Doctrine::HYDRATE_ARRAY);
          if (count($accesses) > 0)
          {
            $result = true;
            break;
          }
        }
        
        // We don't have this privilege as an individual. How about via a group?
        
        // Get group memberships
        $groupIds = aArray::getIds($user->getGroups());

        if (!count($groupIds))
        {
          continue;
        }
        
        // Make sure only groups that have the editor permission can win
        $accesses = Doctrine_Query::create()->
          select('a.*')->from('aGroupAccess a')->innerJoin('a.Group g')->innerJoin('g.Permissions per WITH per.name = ?', sfConfig::get('app_a_group_editor_permission', 'editor'))->innerJoin('a.Page p')->
          where("p.id = ? AND a.privilege = ?", array($pageOrInfo['id'], $privilege))->
          andWhereIn("a.group_id", $groupIds)->
          limit(1)->
          execute(array(), Doctrine::HYDRATE_ARRAY);
        if (count($accesses) > 0)
        {
          error_log("Got one");
          $result = true;
          break;
        }
      }
    }
    return $result;
  }
  
  // Gets only users who are candidates to be editors if given access -
  // not admins who have it regardless. Useful for populating permissions widgets
  public function getEditorCandidates()
  {
    $sufficientCredentials = sfConfig::get(
        "app_a_edit_sufficient_credentials", false);
    $sufficientGroup = sfConfig::get(
        "app_a_edit_sufficient_group", false);
    
    $candidateGroup = sfConfig::get("app_a_edit_candidate_group", false);
    $sufficientGroup = sfConfig::get("app_a_edit_candidate_group", false);
    if (!$candidateGroup)
    {
      echo("No candidate group\n");
      return Doctrine::getTable('sfGuardUser')->createQuery('u')->orderBy('u.username ASC')->fetchArray();
    }
    else
    {
      return Doctrine::getTable('sfGuardUser')->createQuery('u')->innerJoin('u.Groups g WITH g.name = ?', $candidateGroup)->orderBy('u.username ASC')->fetchArray();
    }
  }

  public function getEditorCandidateGroups()
  {
    $p = sfConfig::get('app_a_group_editor_permission', 'editor');
    return Doctrine::getTable('sfGuardGroup')->createQuery('g')->innerJoin('g.Permissions p WITH p.name = ?', $p)->orderBy('g.name ASC')->fetchArray();
  }

  // View candidates = everyone with the view_locked permission whether individually or
  // via a group. On some sites this is a lot of people, so we may find ourselves
  // overriding this for some projects, or just turning off individual permissions
  // for some projects in favor of group permissions. At worst, you'd have to create
  // a group just for Dean Bob
  
  public function getViewCandidates()
  {
    $sufficientCredentials = sfConfig::get(
        'app_a_view_locked_sufficient_credentials', 'view_locked');

    $q = Doctrine::getTable('sfGuardUser')->createQuery('u');
    if ($sufficientCredentials)
    {
      $q->leftJoin('u.Groups g')->leftJoin('g.Permissions gp WITH gp.name = ?', $sufficientCredentials);
      $q->leftJoin('u.Permissions p WITH p.name = ?', $sufficientCredentials);
      $q->andWhere('gp.name = ? OR p.name = ?', array($sufficientCredentials, $sufficientCredentials));
    }
    return $q->orderBy('u.username ASC')->fetchArray();
  }
  
  public function getViewCandidateGroups()
  {
    // All groups are fair game to receive view permissions
    
    return Doctrine::getTable('sfGuardGroup')->createQuery('g')->orderBy('g.name ASC')->fetchArray();
  }
  
  // Gets explicit permissions, not implied permissions such as those held
  // by all admins
  
  public function getPrivilegesInfoForPageId($id)
  {
    $current = Doctrine::getTable('aPage')->createQuery('p')->where('p.id = ?', $id)->innerJoin('p.Accesses a')->innerJoin('a.User u')->orderBy('u.username ASC, a.privilege ASC')->fetchArray();
    $info = array();
    // There will be only one page returned but it's arranged as an array
    foreach ($current as $page)
    {
      foreach ($page['Accesses'] as $a)
      {
        $u = $a['User'];
        $id = $u['id'];
        $info[$id]['id'] = $id;
        $info[$id]['name'] = $u['username'];
        $info[$id]['privileges'][$a['privilege']] = true;
      }
    }
    return $info;
  }
  
  // Gets explicit permissions, not implied permissions such as those held
  // by all admins
  
  public function getGroupPrivilegesInfoForPageId($id)
  {
    $current = Doctrine::getTable('aPage')->createQuery('p')->where('p.id = ?', $id)->innerJoin('p.GroupAccesses a')->innerJoin('a.Group g')->orderBy('g.name ASC, a.privilege ASC')->fetchArray();
    $info = array();
    // There will be only one page returned but it's arranged as an array
    foreach ($current as $page)
    {
      foreach ($page['GroupAccesses'] as $a)
      {
        $g = $a['Group'];
        $id = $g['id'];
        $info[$id]['id'] = $id;
        $info[$id]['name'] = $g['name'];
        $info[$id]['privileges'][$a['privilege']] = true;
      }
    }
    return $info;
  }
}
