<?php

/**
 * PluginaPageToCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginaPageToCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginaPageToCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginaPageToCategory');
    }
}