<?php

/**
 * PluginaEmbedMediaAccountTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginaEmbedMediaAccountTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginaEmbedMediaAccountTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginaEmbedMediaAccount');
    }
}