<?php

/**
 * PluginaMediaItemToCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginaMediaItemToCategoryTable extends Doctrine_Table
{

  /**
   * Returns an instance of this class.
   *
   * @return object PluginaMediaItemToCategoryTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('PluginaMediaItemToCategory');
  }

  public function mergeCategory($old_id, $new_id)
  {
    Doctrine::getTable('aCategory')->mergeCategory($old_id, $new_id, 'aMediaItemToCategory', 'category_id', true, 'media_item_id');
  }

}