<?php
/**
 * 
 * PluginaGroupAccessTable
 * This class has been auto-generated by the Doctrine ORM Framework
 * @package    apostrophePlugin
 * @subpackage    model
 * @author     P'unk Avenue <apostrophe@punkave.com>
 */
class PluginaGroupAccessTable extends Doctrine_Table
{

  /**
   * 
   * Returns an instance of this class.
   * @return object PluginaGroupAccessTable
   */
  public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginaGroupAccess');
    }
}