<?php

/**
 * PluginaCategoryGroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginaCategoryGroupTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginaCategoryGroupTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginaCategoryGroup');
    }
}