<?php
/**
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * @package    apostrophePlugin
 * @subpackage    model
 * @author     P'unk Avenue <apostrophe@punkave.com>
 */
abstract class PluginaImageSlot extends BaseaImageSlot
{

  /**
   * DOCUMENT ME
   * @return mixed
   */
  public function isOutlineEditable()
  {
    return false;
  }
  // We don't need refreshSlot anymore thanks to ON DELETE CASCADE
  // and the new simplified non-API-driven setup
}
