<?php
/**
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * @package    apostrophePlugin
 * @subpackage    model
 * @author     P'unk Avenue <apostrophe@punkave.com>
 */
class PluginaAreaTable extends Doctrine_Table
{

  /**
   * DOCUMENT ME
   * @param mixed $pageId
   * @param mixed $name
   * @return mixed
   */
  static public function retrieveOrCreateByPageIdAndName(
    $pageId, $name)
  {
    $culture = aTools::getUserCulture();
    $area = Doctrine_Query::create()->
      from('aArea a')->
      where('a.page_id = ? AND a.name = ? AND a.culture = ?',
        array($pageId, $name, $culture))->
      fetchOne();
    if ($area)
    {
      return $area;
    }
    $area = new aArea();
    $area->page_id = $pageId;
    $area->name = $name;
    $area->culture = $culture;
    return $area;
  }
}
