<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginaSlot extends BaseaSlot
{
  protected $editDefault = false;
  	
  // By default, the editor for a slot is accessed by double-clicking
  // on an outlined normal view of the slot. That's not appropriate
  // for some custom slot types. Say so by overriding this function
  // in your slot's model subclass and returning false. Then you'll
  // need to implement opening the editor yourself. You can do that
  // in your _normal_view.php by testing $editable and outputting
  // button_to("Edit", $showEditorJS) or similar if it is true.
  // showEditorJS contains ready-to-go jQuery code to hide the
  // normal view and display the editor view.
  //
  // The return value of this method becomes the default setting of
  // the outline_editable option, which can still be overridden
  // manually.

  public function isOutlineEditable()
  {
    return true;
  }

  // You should return a reasonable plaintext representation of your
  // slot's contents for search indexing purposes. A media slot
  // would return the title and description of its contents.

  public function getSearchText()
  {
    return '';
  }

  // Conveniences for slots that use $this->value to store all of their state
  // and wish to store an array there.
  
  public function getArrayValue($default = array())
  {
    if (strlen($this->value))
    {
      return unserialize($this->value);
    }
    return $default;
  }
 
  public function setArrayValue($value)
  {
    if (!is_array($value))
    {
      throw new Exception("Argument is not an array in setArrayValue");
    }
    $this->value = serialize($value);
  }
  
  // Called on the current version of every slot by the a:refresh-slots task, 
  // a periodic task used to update cached information that may be part of each slot's state 
  // and which is subject to occasional change. Right now the best example is the use of 
  // static URLs pointing directly to the media server for performance in
  // media slots. These need refreshing if the frontend controller name changes
  // as part of launch. Also media slots will clean up and remove references to
  // deleted media items when refresh is called. 
  
  public function refreshSlot()
  {
  }
  
  public function editDefault()
  {
    return $this->editDefault;  
  }
  
  public function setEditDefault($editDefault)
  {
    $this->editDefault = $editDefault;
  }
  
  public function isOpen()
  {
    return $this->isNew() && $this->editDefault;
  }
}
