<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginaSlideshowSlot extends BaseaSlideshowSlot
{
  public function isOutlineEditable()
  {
    // We have an edit button and don't use an in-place editor
    return false;
  }
  
  public function getSearchText()
  {
    $text = "";
    $items = unserialize($this->value);
    foreach ($items as $item)
    {
      // backwards compatibility with older stuff in trinity that
      // didn't have the text fields in the slot
      if (isset($item->title))
      {
        $text .= $item->title . "\n";
        $text .= $item->description . "\n";
        $text .= $item->credit . "\n";
      }
    }
    return $text;
  }
  
  public function refreshSlot()
  {
    $slot = $this;
    if (!strlen($slot->value))
    {
      // Not yet set
      return;
    }
    $items = unserialize($slot->value);
    $api = new aMediaAPI();
    $ids = array();
    foreach ($items as $item)
    {
      $ids[] = $item->id;
    }
    $results = $api->getItems($ids);
    if ($results === false)
    {
      echo("Warning: no valid response for slot " . $slot->id . ", leaving it alone on this pass\n");
      return;
    }
    if (!is_array($results))
    {
      throw new sfException('Result should have been array or false, received something else');
    }
    // Some of the items may be gone, accept the new list
    $slot->value = serialize($results);
    if (count($results) < count($items))
    {
      echo("Some images in slideshow have been removed, removing them from slot " . $slot->id . "\n");
    }
    $slot->save();
  }
  
}
