<?php

/**
 * PluginaAudioSlotTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginaAudioSlotTable extends aSlotTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginaAudioSlotTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginaAudioSlot');
    }
}