<?php

/**
 * PluginaFileSlotTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginaFileSlotTable extends aSlotTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginaFileSlotTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginaFileSlot');
    }
}